apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 30%
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: 4uk4upuk/paymentservice:0.0.2