apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: 4uk4upuk/web:1.1
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket: 
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
      - mountPath: /app
        name: app
  initContainers:
  - name: init-web
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - mountPath: /app
        name: app
  volumes:
    - name: app
      emptyDir: {}